language: java
java:
  - "8"

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: test
      after_success:
        - ./gradlew jacocoTestReport coveralls
    - stage: release
      script: ./gradlew build -x test
      after_success:
        - export APP_VERSION=$(cat build/version.txt)
        - export RELEASE_NAME=$(echo "Version $APP_VERSION")
        - if [[ $TRAVIS_TAG =~ ^.*-alpha$ ]]; then export PRE_RELEASE=true; else export PRE_RELEASE=false; fi
        - cd docker && ./prepare-docker-context.sh && ./publish-latest.sh && cd $TRAVIS_BUILD_DIR
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        name: $RELEASE_NAME
        prerelease: $PRE_RELEASE
        file_glob: true
        file: build/libs/*
        skip_cleanup: true
        on:
          all_branches: true
          condition: $TRAVIS_TAG =~ ^release-.*$
      after_deploy:
        - cd docker && ./publish-release-version.sh && cd $TRAVIS_BUILD_DIR

stages:
  - test
  - name: release
    if: type = push AND ( branch = master OR tag =~ ^release-.*$ OR branch =~ ^release/.*$ )
