spring:
  profiles:
    active:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:${civ5.data-dir}/db;DB_CLOSE_ON_EXIT=FALSE"
    username: "civ5"
    password: "civ5"
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: # configure me
    username: # configure me
    password: # configure me

civ5:
  mail.from: # configure me
  data-dir: ./data
  saves-dir: ./data/saves
